const initialData = [
  {
    issueId: "1",
    channelName: "Channel A",
    appName: "Bill Pay",
    severity: "High",
    lessonLearned: "Lesson 1",
    issueDate: "2024-06-10",
  },
  {
    issueId: "2",
    channelName: "Channel B",
    appName: "SIMS Authentication",
    severity: "Medium",
    lessonLearned: "Lesson 2",
    issueDate: "2024-04-10",
  },
  {
    issueId: "3",
    channelName: "Channel D",
    appName: "Wells Fargo banking",
    severity: "Low",
    lessonLearned: "Lesson 3",
    issueDate: "2024-02-10",
  },
  {
    issueId: "4",
    channelName: "Channel A",
    appName: "SIMS Authentication",
    severity: "Critical",
    lessonLearned: "Lesson 4",
    issueDate: "2024-01-10",
  },
  {
    issueId: "1",
    channelName: "Channel C",
    appName: "SIMS Authentication",
    severity: "High",
    lessonLearned: "Lesson 1",
    issueDate: "2024-03-10",
  },
  {
    issueId: "2",
    channelName: "Channel C",
    appName: "Bill Pay",
    severity: "Medium",
    lessonLearned: "Lesson 2",
    issueDate: "2024-09-10",
  },
  {
    issueId: "3",
    channelName: "Channel B",
    appName: "Bill Pay",
    severity: "Low",
    lessonLearned: "Lesson 3",
    issueDate: "2024-12-10",
  },
  {
    issueId: "4",
    channelName: "Channel A",
    appName: "Wells Fargo banking",
    severity: "Critical",
    lessonLearned: "Lesson 4",
    issueDate: "2024-01-10",
  },
  {
    issueId: "1",
    channelName: "Channel A",
    appName: "Bill Pay",
    severity: "High",
    lessonLearned: "Lesson 1",
    issueDate: "2024-08-10",
  },
  {
    issueId: "2",
    channelName: "Channel D",
    appName: "SIMS Authentication",
    severity: "Medium",
    lessonLearned: "Lesson 2",
    issueDate: "2024-10-10",
  },
  {
    issueId: "3",
    channelName: "Channel C",
    appName: "Wells Fargo banking",
    severity: "Low",
    lessonLearned: "Lesson 3",
    issueDate: "2024-11-10",
  },
  {
    issueId: "4",
    channelName: "Channel D",
    appName: "Bill Pay",
    severity: "Critical",
    lessonLearned: "Lesson 4",
    issueDate: "2024-05-10",
  },
  {
    issueId: "1",
    channelName: "Channel C",
    appName: "Wells Fargo banking",
    severity: "High",
    lessonLearned: "Lesson 1",
    issueDate: "2024-06-10",
  },
  {
    issueId: "2",
    channelName: "Channel B",
    appName: "Wells Fargo banking",
    severity: "Medium",
    lessonLearned: "Lesson 2",
    issueDate: "2024-04-10",
  },
  {
    issueId: "3",
    channelName: "Channel C",
    appName: "SIMS Authentication",
    severity: "Low",
    lessonLearned: "Lesson 3",
    issueDate: "2024-02-10",
  },
  {
    issueId: "4",
    channelName: "Channel D",
    appName: "Bill Pay",
    severity: "Critical",
    lessonLearned: "Lesson 4",
    issueDate: "2024-08-10",
  },
];

export default initialData;
